/** Static suggestion lists for structured profile inputs (client-safe). */

export const LANGUAGE_SUGGESTIONS = [
  "العربية",
  "Nederlands",
  "English",
  "Français",
  "Deutsch",
  "Español",
  "Türkçe",
  "العربية المغربية",
  "Português",
  "Italiano",
  "Polski",
  "Svenska",
  "Dansk",
  "Norsk",
  "Ελληνικά",
  "中文",
  "日本語",
  "हिन्दी",
  "اردو",
  "русский",
];

export const EDUCATION_SUGGESTIONS = [
  "High school",
  "Secondary school",
  "Vocational / MBO",
  "Bachelor's degree (HBO)",
  "Master's degree (WO)",
  "PhD / Doctorate",
  "Professional certification",
  "Bootcamp",
  "Self-taught",
];

export const OCCUPATION_SUGGESTIONS = [
  "Software developer",
  "Designer",
  "Teacher",
  "Doctor",
  "Nurse",
  "Engineer",
  "Accountant",
  "Lawyer",
  "Consultant",
  "Sales",
  "Marketing",
  "Student",
  "Freelancer",
  "Business owner",
  "Electrician",
  "Plumber",
  "Cleaner",
  "Driver",
  "Chef",
  "Retired",
  "Unemployed",
];

export const HOBBY_SUGGESTIONS = [
  "Football",
  "Reading",
  "Cooking",
  "Traveling",
  "Photography",
  "Gaming",
  "Fitness",
  "Cycling",
  "Swimming",
  "Music",
  "Movies",
  "Art",
  "Gardening",
  "Fishing",
  "Volunteering",
  "Cars",
  "Fashion",
  "Coffee",
];
